### ISSUE TITLE
Add Option to Use tailwind-cli-extra

### ISSUE THREAD

**Issue by 2mal3** [timonweb/pytailwindcss#10]
### What Is The Problem?

Although pytailwindcss works wonderfully, it is still annoying that so many plugins and especially the widely used [daisyui](https://daisyui.com/) plugin are not supported. This simple, unsupported plugin prevents me and others from using pytailwindcss for several projects. Of course, as mentioned in the caveats section of the readme, not much can be done by pytailwindcss at the moment, since the problem lies within the tailwindcss cli binary used.  However, I recently found something that might help.

### Suggested Solution

The [tailwind-cli-extra](https://github.com/dobicinaitis/tailwind-cli-extra) project has recognized exactly the problem with the standard tailwindcss cli binary and therefore provides an extended version of it, which also has daisyui plugin built in. pytailwindcss could offer this version of the tailwindcss binary as an alternative to the standard one, which could be switched by setting a special environment variable, for example.  
tailwind-cli-extra is fully automated, so the binaries should always be up to date.

**Comment by jrvidotti** [comment]
https://github.com/2mal3/pytailwindcss-extra
