### ISSUE TITLE
The `content` key is missing or empty.

### ISSUE THREAD

**Issue by guillermohs9** [timonweb/pytailwindcss#3]
Hi! After installing the package I run the command to generate the output css file but I get the following error:

```
(venv) [guillermo@arch guarde]$ tailwindcss -i input.css -o style.css --minify

warn - The `content` key is missing or empty. Please populate the content key as Tailwind generates utilities on-demand based on the files that use them. For more information see the documentation: https://tailwindcss.com/docs/content-configuration

Done in 233ms.
```

I'm guessing I must edit the content key in the tailwind.config.js file but I can't seem to find it inside my venv.
Sorry if it's a silly issue...
Cheers

**Comment by timonweb** [comment]
You need to init configuration, run `tailwindcss init` and it will create intitial `tailwind.config.js` file for you.

**Comment by guillermohs9** [comment]
So it was a silly issue... You're absolutely right. The worst part is I've used the tailwind-cli standalone tool in the past, and I knew this was a required step. Thanks!
